### ISSUE TITLE
CustomAction seems not to run in c#

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#1003]
I tried both in TE2 and TE3 and the issue is only present in TE2 

running a script calling a different CustomAction raises no error, but no action happens. 
the same operation in TE3 does the trick . 

This is the customAction being called (stored as "Dynamic Measure" 
https://github.com/bernatagulloesbrina/Dynamic-Measures/blob/main/Dynamic%20Measure%20ULTIMATE%20Script.csx 

And this is the script from which it is called
https://github.com/bernatagulloesbrina/TabularEditor-Scripts/blob/main/Advanced/One-Click%20Macros/Alert%20Summary%20Measures.csx

Regards!

**Comment by otykier** [comment]
Hi @bernatagulloesbrina 
I've finally had the time to look into this issue. In your script # 2 you're calling `Model.CustomAction(...);`. This essentially means that you are passing `Model` as the current selection to the context of the custom action (script # 1). So for this to work, you must make sure that the Custom Action is saved with "Model" as one of the valid contexts, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/8976200/184090513-59a8d635-dfba-4ffb-8dc1-1fe22322a3f2.png)

Since your script # 2 requires the user to select a table, maybe you wanted to pass all the measures on that table to script # 1? In that case, you should write:

```csharp
CustomAction(Selected.Table.Measures);
```

Hope this makes sense.
