### ISSUE TITLE
How to turn off Auto Date/Time 

### ISSUE THREAD

**Issue by mohitnayar123** [TabularEditor/TabularEditor#1009]
Is there a property in Power BI Model when opened in TE3/TE2 to turn off the auto date time?

**Comment by otykier** [comment]
This is unfortunately not possible, as PBI Desktop does not store this property in the model metadata (but rather somewhere else in the pbix file, which TE does not have access to). However, you can easily determine if a model uses auto date/time due to the presence of the hidden date tables containing GUIDs in their names.

If you encounter such a model, open it in PBI Desktop and disable auto date/time. If you can’t open the model in Desktop (for example if the model has been modified through the XMLA endpoint), simply delete the autogenerated date tables with TE.
