### ISSUE TITLE
Loosing credentials when deploying model

### ISSUE THREAD

**Issue by KristofferSisseck** [TabularEditor/TabularEditor#1017]
Hi Tabular Editor

I have some issues when I de deploy my model. Whenever I do so using Tabular Editor, I am loosing my credentials.
My SQL Server is 2019  and the Compatability Level of analysis Services is 1500. 
I read Issues 194. If the model is 1400 or lower that should happend. But is it still the case when my model is 1500?
https://github.com/TabularEditor/TabularEditor/issues/194

Maybe there is something I am missing when deploying? 

That you for an awesome tool!

Kind Regards
Kristoffer Sisseck

**Comment by otykier** [comment]
Unfortunately, the issue remains with CL 1500 (and probably future CLs) as well. In fact, it doesn't have much to do with the CL, but rather it is how the AS engine treats the credentials on Structured Data Sources, when a deployment is made. If you are loading data from a relational data source such as a SQL Server, consider switching over to Provider (aka. Legacy) Data Sources, since these do not have this issue. If you're not able to switch to Provider data sources, you'll have to run a TMSL script to set the password after deployment (as described in #194), or alternatively, use a c# script inside Tabular Editor to set the password before deploing.

**Comment by KristofferSisseck** [comment]
Hej Daniel, 

Thank you for a quick respons. I now makes sense to me. I will look into the diffent solutions that you provided. 

Kind Regards
Kristoffer
