### ISSUE TITLE
How to make Visual Studio error check for TE2

### ISSUE THREAD

**Issue by bernatagulloesbrina** [TabularEditor/TabularEditor#1035]
hello 

I noticed that some parts of c# 6.0 do not compile in TE2 
nameof [is supposed to be part of it,](https://www.c-sharpcorner.com/UploadFile/16101a/nameof-operator-a-new-feature-of-C-Sharp-6-0/) but does not compile in TE2 for example 
TE3 does compile, but execution of 

Output(nameof(Model)); 

spins forever and produces no result 

anyway, I'd like to know if there's anyway to make visual studio mark as error anything that will not work in TE2
or at least part of it 

I saw that 
variable is null must be variable == null 
output parameters must come first
if you start naming arguments you need to keep going all the way to the end 

all these things do work in TE3 but not in TE2

**Comment by bernatagulloesbrina** [comment]
nameof works fine in TE3 if you feed it a variable instead of the actual model as I did before...

**Comment by bernatagulloesbrina** [comment]
It does work in TE2 too -- just need to make sure that the argument of "nameof" is a variable and not the model, that's all. 

By the way, if anyone reachies this site, I did find a way to make Visual Studio error check for C# 6-0, is documented here 

https://www.esbrina-ba.com/writing-tabular-editor-c-scripts-like-a-boss/

**Comment by otykier** [comment]
TE2 uses the C# compiler that ships with [.NET Framework](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language#minimum-sdk-version-needed-to-support-all-language-features). As can be seen, this only supports C# 5 language features (there are a few minor differences between C# 5.0 and C# 6.0).

Since you have Visual Studio installed, why not [instruct Tabular Editor 2 to use the Roslyn compiler](https://docs.tabulareditor.com/te2/Advanced-Scripting.html#compiling-with-roslyn), instead of forcing C# 5.0 syntax? :)

**Comment by bernatagulloesbrina** [comment]
The reason is that I want my scripts to be as widely compatible as possible :) 
I'll limit the version to 5 then, just to be sure.
