### ISSUE TITLE
Azure DevOps : Successful Deployment but Release Pipeline in error

### ISSUE THREAD

**Issue by evandadure** [TabularEditor/TabularEditor#1054]
Hello ! I'm currently using the Tabular Editor CLI in Azure DevOps pipelines to automate my tabular cubes deployments.
Everything was working well (thanks to @otykier guidelines) until I implemented the pipelines for a new cube which uses a lot of calculated tables and columns.

Here is the command I'm executing via the TabularEditor CLI (**version  2.12.4**) :

`TabularEditor.exe "_$(Build.DefinitionName)\drop\Model.bim" -S "_$(Build.DefinitionName)\drop\UpdateCubeDatasources.cs" -D "Provider=MSOLAP;Data Source=$(AASURL);User ID=$(AASLogin);Password=$(AASPassword)" "$(DeployedCubeName)" -O -C -R -V -E -M -P`

When running the pipeline to deploy the cube, there are two scenarios : 

1. This cube already exists and has already been processed. In this case, the deployment happens, and TabularEditor returns no error, so the pipeline is in the "ok" state : 

![image](https://user-images.githubusercontent.com/22052945/202157311-52ddcd8a-8e27-4cc5-8738-60456a17669e.png)

2. This cube does not exist yet (or has not been processed yet). In this case, **the deployment still happens**, **but TabularEditor returns many errors, so the pipelines is in the "error" state:**

![image](https://user-images.githubusercontent.com/22052945/202157226-0e587d04-b0ec-4a00-9080-a2ea4f97c5a6.png)

By looking at the logs, we can see that right before the errors, the **deployment has succeeded**.
After checking my AAS instance, the cube has indeed been deployed, and the full process works fine... So why is TabularEditor returning these errors but still deploying my cube ?
Also, once the newly deployed cube has been processed (even after a _"failed"_ deployment), if I run the **same** release again, the deployment executes well, without any error.

I'm currently trying to identify what's different in this cube compared with all other cubes, but I was wondering if someone already faced this issue?

**Additonal notes :**

- The "_UpdateCubeDatasources.cs_" script is simply modifying the (structured) sources of the Model.bim file of each cube.
- I'm using exactly the same command, build/release pipelines, and AAS Instances for all other cubes, and never faced this issue before.

**Comment by otykier** [comment]
Hi Evan,
The deployment indeed completes successfully (as you highlighted in the output). However, since you included the `-E` switch in the command line, Tabular Editor will treat any object in the model that has an error state (after deployment) as an error. There are scenarios where you want to react to such errors, which could be DAX syntax errors - for example when validating a Pull Request as a sort of unit test.

If you know it is safe to ignore the errors, you can omit the `-E` switch. To understand why the errors occur, connect to your model with TE after deployment (but before processing) and inspect objects that have an error state. From the error messages, it looks like you have some DAX code that produces a result with an unexpected data type, when the model has no data. This could arise in various ways, from using IF, SWITCH, SELECTEDVALUE, etc.

**Comment by evandadure** [comment]
Hi Daniel,

Thank you very much for your fast answer, we'll have look at the error metadata in TR. Have a great day!
