### ISSUE TITLE
unexpected cube changes %20 replacing trailing spaces

### ISSUE THREAD

**Issue by sbrownatvr** [TabularEditor/TabularEditor#1066]
Version 2.17

**Describe the bug**
when changing anything in the cube proj I can see additional files updated as well that I don't recognize:
especially weird are these with %20 in place of a trailing space.

The non-Variance measures have '"isDataTypeInferred": false,' property deleted

**To Reproduce**
1. Open database from file.
2. Make my changes (or even dont make a change)
3. Save
4. my git branch changes now show (for example) 'Average Daily Units % Occupied .json' to 'Average Daily Units % Occupied**%20**.json' which is not a change I made.

**Expected behavior**
Behavior as expected before last few days.  Now I get the change being triggered although I did not initiate the change.

**Observed behavior**
Additional changes in git changes on my branch that I did not initiate, replace trailing space with '%20'

**Application specifics**
 - Tabular Editor 2.17.1
 - Semantic Engine used: [Power BI Desktop, Azure Analysis Services, SSAS 2016, etc.]
 - Model Compatibility Level: 1400

**Additional context**
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/122268686/211286762-52edb4a9-b5a4-4702-b373-72a6964fa4d1.png)

**Comment by o-o00o-o** [comment]
In case it helps clarify, we are seeing the following behaviour after just saving an existing model with the same version of tabular editor that we used to generate it originally

1. some IsDataTypeInferred:false properties are removed

![image](https://user-images.githubusercontent.com/13693159/211378424-422888d6-340f-421e-ae44-334461f1d9e1.png)

2. and the filenames having trailing spaces encoded as %20 as the OP screenshot shows

**Comment by mlonsk** [comment]
Hi @sbrownatvr and @o-o00o-o 
I have not been able to reproduce this on my end. 
Have you by any chance changed the serialization settings recently in Tabular Editor, and could you send a screenshot of how they are set up?
Thank you

**Comment by sbrownatvr** [comment]
Good morning Morten,

Thanks for coming back to us on this, please find the screenshots below.

I haven't changed any of these settings and have not seen this occur before now.  Please let us know if there is any further information we can provide.

Appreciate your help.

Thanks,
Steve

***@***.***

***@***.***

**Comment by mlonsk** [comment]
Hi Steve @sbrownatvr 
I cannot see a screenshot, perhaps it didn't get it in correctly when answering through mail?

**Comment by sbrownatvr** [comment]
![TabularEditor - Screenshot 2023-01-17 115251](https://user-images.githubusercontent.com/122268686/212892295-13792c5d-935b-48b8-a7fe-8c8fed800836.png)
![TabularEditor - Screenshot 2023-01-17 115311](https://user-images.githubusercontent.com/122268686/212892298-ef98c6e3-5d04-4c5b-bd1e-c72f4f4c98d1.png)

**Comment by sbrownatvr** [comment]
Apologies, didn't realise couldn't replay by email.  Hopefully this works better?  just uploaded direct to github.

**Comment by mlonsk** [comment]
@sbrownatvr 
Hi Steve
that is great. Will see if I can reproduce it on my end.

**Comment by mlonsk** [comment]
Hi Steve  (@sbrownatvr )
Changing trailing spaces to %20 have been implemented in TE2 since v. 2.16.6 due to the this issue #952. In short it is a way to ensure that all objects with trailing spaces are saved, as windows will cut off trailing spaces on e.g. folders.

So if you have recently updated to a version beyond 2.16.6, that would explain why this was not an thing before, but is now. 
The reason you are seeing them on the objects is thus that the objects have a trailing space at the end of the name. 
(At least this way it becomes a bit clearer if you have trailing spaces )

For the other part where  IsDataTypeInferred:false is removed I suspect that is due to your serialization settings where you have "ignore inferred properties" checked. 

We will keep this open as a bug, as we will look into if we can implement it so that the JSON objects do not get the %20 in future versions, as it is probably only required for folders and not the JSON objects themselves.

**Comment by mlonsk** [comment]
This issue should be solved in 3.4.1 and later versions

**Comment by otykier** [comment]
For Tabular Editor 2, this is now fixed in [2.17.3](https://github.com/TabularEditor/TabularEditor/releases/tag/2.17.3)
