### ISSUE TITLE
BPA rule: Set IsAvailableInMDX to false error returned: no attribute hierarchy enabled

### ISSUE THREAD

**Issue by martinerr** [TabularEditor/TabularEditor#1067]
When I set "Available in MDX" to False for some columns and try to save, I get the following error:
"Failed to save modification to the server.  Error returned: 'The column XXX does not have an attribute hierarchy enabled.'.

Could somebody help me with this? The BPA is suggesting these columns. For most columns it is possible to do but for some it is not and I cannot find any logic to that yet. Where can I see if a column does not have an attribute hierarchy enabled? And would it be possible to exclude these then also from the BPA rule? 
Thank you!

**Comment by otykier** [comment]
Setting "AvailableInMDX" to false, disables the creation of an attribute hierarchy for this column. Some columns must have attribute hierarchise, or the save/deployment will fail as you have seen, however this is poorly documented from Microsoft's side. You can find some info on Chris Webb's blog post: https://blog.crossjoin.co.uk/2018/07/02/isavailableinmdx-ssas-tabular/

Regarding the BPA rule - I see you already created an equivalent post [here](https://github.com/microsoft/Analysis-Services/issues/190), which is the right place to discuss this, as Tabular Editor does not ship with any BPA rules out of the box, so I'm closing this issue here.
