### ISSUE TITLE
Class UsedByPartitions not giving the correct result when using Incremental Refresh Policy

### ISSUE THREAD

**Issue by justBlindbaek** [TabularEditor/TabularEditor#1076]
I'm using a subset of the "official" BPA rules as part of a build pipeline in Azure DevOps. After enabling Incremental Refresh Policy on one of the fact tables I'm getting a violation on the "[Maintenance] Remove data sources not referenced by any partitions" rule.

The expression for the rule is: UsedByPartitions.Count() == 0

I hereby think there must be a bug in the "UsedByPartitions" class as it apparently don't take into account that partitions generated by an Incremental Refresh Policy don't have a direct reference to a Data Source. The reference is part of the sourceExpression on the table level.

I creates a new Structured Data Source (Power Query) just for this one fact table, so I could setup the IR policy. The rest of the tables/partitions in the model uses another Provider Data Source (Legacy).

This is the class: https://docs.tabulareditor.com/api/TabularEditor.TOMWrapper.DataSource.html#TabularEditor_TOMWrapper_DataSource_UsedByPartitions

**Comment by otykier** [comment]
Hi Just. 

`UsedByPartitions` only considers explicit object references at the TOM level. That is, when you set the `DataSource` property of a partition to point to one of the data sources in your model.

Unfortunately, M queries do not reference the data sources at the TOM level - instead, they may or may not reference a data source through the M expression. However, it is not trivial to detect this, since the reference could happen through one or more shared expressions, etc. In any case, TE2 is not able to parse the M query to figure out if it references any partitions, so we're not able to change the behavior of `UsedByPartitions`.

However, there is a simple workaround, provided that you explicitly reference the data source in the `SourceExpression` M query on the table. For the "[Maintenance] Remove data sources not referenced by any partitions" rule, modify the expression as follows:

```
UsedByPartitions.Count() == 0 
and not Model.Tables.Any(SourceExpression.Contains(OuterIt.Name))
```

`Model.Tables.Any(SourceExpression.Contains(OuterIt.Name))` checks if there are any tables where the `SourceExpression` string contains the name of the data source (`OuterIt`).

We could also extend the BPA rule to M partitions in general:

```
UsedByPartitions.Count() == 0 
and not Model.Tables.Any(SourceExpression.Contains(OuterIt.Name))
and not Model.AllPartitions.Any(Query.Contains(OuterIt.Name))
```

Hope this helps!

**Comment by justBlindbaek** [comment]
Thank you very much for the prompt reply. As a first to get going, I adjusted the scope of the rule to only work on `ProviderDataSource`. But now I will implement your suggestion.

I created a [issue on the BPA rules](https://github.com/microsoft/Analysis-Services/issues/197), so Michael Kovalsky can implement your suggestion into the official BPA rules.

**Comment by otykier** [comment]
Glad to be of help!

> I adjusted the scope of the rule to only work on ProviderDataSource

Yeah, that's a good option to get rid of the false positives in your case. However, please be aware that M expressions can reference ProviderDataSources and legacy partitions can reference StructuredDataSources, so this approach should not be used in general :)
