### ISSUE TITLE
Can't view table data in VS after updating .bim in TE2

### ISSUE THREAD

**Issue by ralphsartin** [TabularEditor/TabularEditor#1080]
I made a number of adjustments to my model in Tabular Editor, mostly based on best practice analysis.  After saving the changes and then opening the solution in Visual Studio (2019), the table data does not show on three of my tables after processing them.

The changes I recall included removing availability in MDX, formatting numerical fields from general to whole numbers, adding table names to fully-qualify column names, adding descriptions to hierarchies...  there were some others, but I left them out if I know they affected tables I can still see the data in.

**Comment by ralphsartin** [comment]
Update - I updated the table keys for the affected tables to be available in MDX again, and the problem was resolved.  Maybe table keys, though hidden, shouldn't be recommended in the DISABLE_ATTRIBUTE_HIERARCHIES recommendation?

**Comment by otykier** [comment]
I don't know why Visual Studio requires that IsAvailableInMdx = true on hidden key columns. It should not be a problem for the end-users of your model (i.e. those who would typically be querying the model using Excel, Power BI or other client tools). So instead of changing the rule, I would recommend reporting this as a bug to the [Analysis Services Projects extension for Visual Studio team](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjects).
