### ISSUE TITLE
Dropping Credentials when deploying even on Legacy sources

### ISSUE THREAD

**Issue by KristofferSisseck** [TabularEditor/TabularEditor#1100]
Hi Daniel, 

Jeg anvender tabular Editor til at deploy min model. Jeg brugte førhen Power Query som data source,  men du foreslog at jeg skulle skifte til "Legacy" metoden.   Jeg har nu skiftet til dette, men oplever desværre stadigvæk at jeg mister mine credentials når jeg deployer. 

Jeg anvender SQL server authenticating med et dertilhørende Username og Password imod en Azure SQL database. 

Jeg kan se når jeg scripter via SSMS at mit password netop er forsvundet.   Mangler jeg at sætte et flueben et sted når jeg anvender Legacy metoden? Og at den stadigvæk smider mine credentials?    Eller vil den altid gøre dette? 

Du assisterede tilbage i issue 194.

Mange tak for et fedt produkt!

Mvh
Kristoffer

**Comment by otykier** [comment]
Hi Kristoffer,
It is not possible to obtain the password through scripting in SSMS - even if the password was properly assigned during deployment. Passwords are "write-only" in Analysis Services.

Since your Model.bim file should also not contain the password, please make sure to disable the "deploy data source" option whenever you perform a deployment. This way, the credentials configured for the existing (legacy) data sources are retained.

![image](https://user-images.githubusercontent.com/8976200/235926433-612ef808-82a2-4fce-90c0-985f39bee035.png)

With this approach, I only need to specify the credentials in the connection string once. For example, I can use SSMS to script the data source, add the password to the connection string, and run the script:

```json
{
  "createOrReplace": {
    "object": {
      "database": "TabularProject6",
      "dataSource": "SQLDW"
    },
    "dataSource": {
      "name": "SQLDW",
      "connectionString": "Provider=MSOLEDBSQL.1;Data Source=te3-training-sql.database.windows.net;Persist Security Info=True;User ID=sqlreader;Password=<my password here>;Initial Catalog=AdventureWorksDW2019",
      "impersonationMode": "impersonateServiceAccount",
      "annotations": [
        {
          "name": "ConnectionEditUISource",
          "value": "Others"
        }
      ]
    }
  }
}
```

The username/password will be retained, as long as I do not overwrite data sources as part of my deployment.

**Comment by KristofferSisseck** [comment]
Hi Tabular

Thank you for a quick respons!

And yes of course I need to remove the “Deploy Data Source”  after removing that check mark everything is deploying smoothly!


Kristoffer Tving Sisseck
Senior Data and Analytics Consultant
+45 60 21 38 64
Vibeholms Allé 16
2605 Brøndby

***@***.***

www.biteq.dk<http://www.biteq.dk/>
***@***.***<https://www.linkedin.com/company/biteq>
