### ISSUE TITLE
Deployment fails for model at Compatibility Level 160x

### ISSUE THREAD

**Issue by TomekZag** [TabularEditor/TabularEditor#1121]
Deployment of model to AAS with Compatibility Level set to 160x (checked for 1601 and 1604 so far) fails, when called via CLI in Azure DevOps Release pipeline. 

**To Reproduce**
Execute Azure DevOps Release Pipeline with CLI.
Error Message: 
Tabular Editor 2.19.0 (build 2.19.8566.40387)
Loading model...
Loaded script: _Artifacts\AAS\Automation\SSAS\UpdateConnectionString.cs
Executing script 0...
Switching connection string placeholders...
Deploying...
##[error]Deployment failed! A connection cannot be made. Ensure that the server is running.
##[error]Cmd.exe exited with code '1'.

**Expected behavior**
Deployment succeeded for Compatibility Level 1601x via Azure DevOps Release Pipeline.

**Observed behavior**
I changed Compatibility Level to 1601 to use Format String Expression in a measure. 
Deployment of 1601 works perfectly from the Tool directly, using Model -> Deploy option, but not from CLI in Azure DevOps Release Pipeline.
Azure DevOps Release Pipeline deployment uses -D option with connection string retrieved from KeyVault. Connection string has the structure like below:

Provider=MSOLAP;Data Source=asazure://region/servername;User ID=app:appId@tenant;Password=xxxxxxxx;Persist Security Info=True;Impersonation Level=Impersonate

Full CLI script:

'$(System.DefaultWorkingDirectory)/_Artifacts/AAS/Tools/TabularEditor/TabularEditor.exe "_Artifacts\AAS\$(SSASModelName)\$(SSASModelName).bim" -S "_Artifacts\AAS\Automation\SSAS\UpdateConnectionString.cs" -D "$(SSASConnectionString)" "$(SSASModelName)" -C "|ConnectionString|" "$(SSASSourceConnectionString)" -O -P -R -V -E'

Please notice that connection string to the underlying source is also stored in the KeyVault and replaced with -C option.

**Application specifics**
 - Tabular Editor 2.X version: Version 2.18.2 + 2.19.0
 - Semantic Engine used: Azure Analysis Services (max. support of 1604).
 - Model Compatibility Level: 1601

**Additional context**
Deployment of former model's version with Compatibility Level 1500 (without Format String Expression) and usage of TE version 2.17.1 worked perfectly with the same CLI structure in the Release Pipeline and same connection strings retrieved from the KeyVault.

**Comment by otykier** [comment]
I don’t think AAS support CompatibilityLevels above 1600 yet.

**Comment by TomekZag** [comment]
Hi Daniel @otykier, thank you for the quick response!
As per my check, the AAS we use, supports versions above 1600:

![AAS](https://github.com/TabularEditor/TabularEditor/assets/140519340/8953028a-4f56-4ec6-9ecb-9c85164e4913)

Please notice that I am able to deploy the model with CompatibilityLevel = 1604 to the target AAS server using Model -> Deploy action in GUI, version 2.19.0. The problem appears only in the command line deployment using Azure DevOps Release Pipeline.

**Comment by otykier** [comment]
Hi @TomekZag
Thanks for clarifying.

The GUI uses exactly the same code for deploying the model as the CLI, so if the deployment works through the GUI, it should work through the CLI as well. From the error message received (`Deployment failed! A connection cannot be made. Ensure that the server is running.`), it looks like the command fails when Tabular Editor tries to open the connection against Analysis Services, and this step is handled by the AMO/TOM library provided by Microsoft. However, this step should not be affected by which compatibility level the model is using.

You mentioned that deployment through CLI with CL 1500 works fine - are you still able to deploy the exact same model, to the exact same server, with the same CLI script when the model is at CL 1500? If yes, have you tried to deploy the CL1604 model as a new database, instead of overriding the existing one? Maybe the AMO/TOM encounters an error it can't handle when attempting to upgrade the destination model, which somehow causes the connection to be broken.

**Comment by TomekZag** [comment]
Hi Daniel @otykier,
I checked again the whole setup of the Pipeline and it occurred that I was missing some .dlls and .exe.config file in the artifacts' list built and used for CLI deployment:

- System.IO.Compression.dll
- System.Net.Http.dll
- System.ValueTuple.dll
- TabularEditor.exe.config

After including all abovementioned files within the same folder of .exe file location I was able to deploy up to 1604 Compatibility Level!
Deployment of 1500 CL using version 2.17.1 was possible without .exe.config, and that's why I wasn't including this one for the build artifact for upper versions (2.18.2 & 2.19). My mistake, sorry for inconveniences!
