### ISSUE TITLE
CS2001 - Source file could not be found

### ISSUE THREAD

**Issue by CeciliaW888** [TabularEditor/TabularEditor#1163]
Hi Daniel,

Thank you for creating such an amazing tool. I really love the BPA tool and Apply Fix shortcut. It was working really well.

However, recently my company IT was fixing some other issues on my laptop and he emptied the Temp folder in my C drive. Since then, the advanced scripting doesn't work. Below is the error msg I got (I'm connected to the PBI desktop).

<img width="306" alt="CS2001 error" src="https://github.com/TabularEditor/TabularEditor/assets/110141407/482d663e-9a4c-43df-8514-0a2d0218762e">

I tried to upgrade to the latest TBE version, uninstall and reinstall, and install it in a different location other than C drive. I also tried to google this issue but none of those worked. It's a company PC so I can't make any changes to the C drive or Temp folder (in the C drive).

I'm not sure if this is related to the Temp folder. So I changed the compiler folder (File > Preference > Advanced Scripting > Compiler Paht), then I got the below error.

<img width="335" alt="TE Error" src="https://github.com/TabularEditor/TabularEditor/assets/110141407/a8432fc8-fe6a-4646-911e-c9038c389b21">

Could you please help me with this issue? Really appreciate your help and time.

Cheers,

Cecilia

**Comment by otykier** [comment]
Was the `C:\windows\Temp` folder itself deleted? Or maybe the access permissions for the folder was changed? That seems like an error on the part of the person who fixed your laptop, and this is going to cause you other issues as well, not just with Tabular Editor.

If you change the Compiler Path, you should provide a path to a custom installation of the C# compiler, such as the Roslyn compiler from Visual Studio. Otherwise, please leave this setting blank (Tabular Editor does not include a custom C# compiler). [More information](https://docs.tabulareditor.com/te2/Advanced-Scripting.html#compiling-with-roslyn).

**Comment by CeciliaW888** [comment]
Hi Daniel,

Thank you so much for the prompt reply. I asked our company IT to open the temp folder with his credentials and then the C# script magically worked again. It was ok even after he closed the folder🥲

I'll close the ticket now.

Many thanks,

Cecilia
