### ISSUE TITLE
Unable to load Tabular Model (Compatibility Level 1200+)

### ISSUE THREAD

**Issue by sai-naresh-1234** [TabularEditor/TabularEditor#1171]
Hello @otykier 

We are trying to integrate Tabular editor in .NET core web Api but we are getting the below issue. Can you please help on to fix this issue.
"Unable to load Tabular Model (Compatibility Level 1200+) from .src\model.bim. Error: The type initializer for 'Microsoft.AnalysisServices.Core.Utils' threw an exception".

![image](https://github.com/TabularEditor/TabularEditor/assets/152960621/4f5577d1-481b-4330-a4d1-095a6b303167)

When we dig into the deep we got the below issue 
![image](https://github.com/TabularEditor/TabularEditor/assets/152960621/c5b48dcc-3d1d-44e7-aad3-9a6274dd231a)

Is Tabular editor doesn't support in .net core? It is working fine in .NET framework 4.8 version.

**Comment by otykier** [comment]
Tabular Editor 2 is targeting .NET Framework, so you may hit various issues if you attempt to load .NET Core assemblies. Since you're working with the Tabular Editor 2 source directly, you should change the compilation target of the TOMWrapper (and any other Tabular Editor projects you're using) to the appropriate .NET version (for example, .NET 6).
