### ISSUE TITLE
IT department rejected Tabular Editor 2, Wants newer .Net Runtime more recent version from 4.6

### ISSUE THREAD

**Issue by ghochste** [TabularEditor/TabularEditor#1174]
Having issues getting approval to install Tabular Editor 2.X in our environment as it uses .Net Version 4.6

Is it possible to have Tabular Editor use a more recent version of the .Net ?

We are trying to get Tabluar editor 2 installed in our environment for managing datasets etc

**Comment by otykier** [comment]
Tabular Editor 2.x uses .NET Framework 4.8, which is the latest .NET Framework release, which also ships natively with Windows 10 / Windows 11. We have no plans to go beyond .NET Framework (i.e., .NET 6/.NET 8), as this would require substantial changes to the application and also require a new deployment model, since none of the newer .NET runtimes ship with Windows. Moreover, [.NET Framework 4.8 is still fully supported by Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet-framework), and there are no plans to deprecate it, that we're aware of.
