### ISSUE TITLE
GetAnnotation shows twice in tooltips on a column

### ISSUE THREAD

**Issue by m-kovalsky** [TabularEditor/TabularEditor#1197]
**Describe the bug**
GetAnnotation shows twice in tooltips on a column.

**To Reproduce**
See screenshot

**Expected behavior**
It should shows just once

**Observed behavior**
<img width="484" alt="image" src="https://github.com/TabularEditor/TabularEditor/assets/29556918/b06b973a-ea4e-46f1-8050-92f0c2a0c8fc">

**Application specifics**
 - TE 2.24.0

**Comment by otykier** [comment]
I think this is because there are two different overloads of the `GetAnnotation` method, but admittedly, that's not clear from the popup. Will see what I can do to improve this, thanks!

**Comment by m-kovalsky** [comment]
Yes, I realized this as well. I think one takes the name and one takes an integer (0,1,2..). Just found it a bit odd that it shows up twice. Thanks!

**Comment by otykier** [comment]
I've made [a fix](https://github.com/TabularEditor/TabularEditor/releases/tag/2.25) so that the method is now only displayed once, and the tooltip then displays the overloads. Moreover, the tooltip now also displays the type of the parameters (int vs. string in this case):

![image](https://github.com/TabularEditor/TabularEditor/assets/8976200/f471e68e-f195-4522-b169-bb06ca5ba24d)
