### ISSUE TITLE
BPA Rule to validate RLS

### ISSUE THREAD

**Issue by fmms** [TabularEditor/TabularEditor#1198]
**What are you trying to achieve?**
I want to build a BPA rule to ensure that we have setup RLS according to our standards.

**What have you tried so far?**
As a manual C# script I can achieve this with:
```
var missingRLS = "";
foreach(var r in Model.Roles) {
  foreach(var t in Model.Tables) {
    if (t.Name.StartsWith("fact_" ))
    {
      var exists = false;
      foreach (var tp in r.TablePermissions) {
        if (tp.Role.Name == r.Name && tp.Table.Name == t.Name) exists = true;
      } 
      if (!exists) {
        missingRLS += "table: " + t.Name + "\t role: " + r.Name + "\n";
      }
    }
  }
}
Info (missingRLS);
```

How can i convert the above in a BPA rule?

**Comment by otykier** [comment]
So just to make sure I understand this correctly, you want to make sure that every table in the model that has a name starting with "fact_", has at least one TablePermission object?

A couple of clarifying questions:

- Are you aware the TablePermission objects can exist with an empty Filter Expression? (Thus effectively not providing any RLS)
- Are you aware that one table can have multiple TablePermission objects, up to the number of roles in the model? Should the rule ensure that every role has a table permission for every fact, or just that at least one role has a table permission?
- Are you aware that it is generally considered [bad practice to apply RLS directly to fact tables](https://learn.microsoft.com/en-us/power-bi/guidance/rls-guidance#optimize-rls)?

**Comment by fmms** [comment]
@otykier thanks for your reply.

The idea is a different: I want to validate that every table starting with `fact_` has explicit RLS for every role in the data model.
Thus my idea is to first build the cross product of `Model.Roles` and `Model.Tables` and then validate that for each combination I can find such an element (based on `r.TablePermissions`)

Regarding your clarification questions:
1. yes very aware, thus using the approach of cross product. That is actually the reason for that code...
2. Yes very aware.
3. Yes aware, though for the model at hand with different subject areas combined we considered this a good exception. There is lots of people that may see one company code for one subject area and different company codes for a different subject area...


My script above returns what i want -- I assume. Though, I am not sure how to transform that into a BPA rule ...

**Comment by otykier** [comment]
Since you said you want to check that every `fact_` table has explicit RLS for every role, I assume you also want to check that the FilterExpression property on the TablePermission object is non-empty.

If so, the below rule expression should do the trick. Select "Tables" in the **Applies to** dropdown.

```
Name.StartsWith("fact_", StringComparison.OrdinalIgnoreCase)
and
Model.Roles.Any(string.IsNullOrEmpty(current.RowLevelSecurity[it]))
```

The first part is trivial. The second part performs the cross check of every role against every table. `current` references the current table in the iteration (i.e. the current object in the collection of objects chosen in the **Applies to** dropdown). `it` refers to the object in the inner iterator, in this case, the `Model.Roles` collection.

Tables have a [`RowLevelSecurity`](https://docs.tabulareditor.com/api/TabularEditor.TOMWrapper.Table.html#TabularEditor_TOMWrapper_Table_RowLevelSecurity) property, that we can index into using a role (or the name of a role). The property returns the string currently assigned as RLS, or null, if no string is specified or no TablePermission object exists.

**Comment by fmms** [comment]
@otykier thank you so much this does exactly what we wanted to achieve.
