### ISSUE TITLE
Can I open a direct lake Model.Bim file and save it as Import Mode?

### ISSUE THREAD

**Issue by patrickbcox** [TabularEditor/TabularEditor#1224]
I would like to convert a Direct Lake Semantic Model to import mode and I am not sure if this is possible.  I am able to connect to the model and I know how to save the model.bim file and then Re-Deploy, however I am not sure if there is a setting(s) that I can change to make the model import instead of direct lake.

thanks!

**Comment by mlonsk** [comment]
Hi @patrickbcox 
While it certainly should be possible to do this, it does require undoing many of the particular settings that Direct Lake models contain. I do not know of a guide available, but you could check out this blog on how to manually create Direct Lake models and reverse engineer that process: https://blog.tabulareditor.com/2023/08/23/fabric-direct-lake-dataset/

**Comment by otykier** [comment]
I wrote a small C# script that performs this conversion (and a blog post to go along with it). Check it out here: https://www.linkedin.com/pulse/converting-direct-lake-model-import-daniel-otykier-h2chf

**Comment by patrickbcox** [comment]
Hi @otykier ,
I ran your script and it appeared to work so I then published the model but something is wrong.  I am not able to download or open the model in the PBI Service and when I try to refresh I am getting a data error.  Any ideas about something I could be missing?  Thanks.

**Comment by otykier** [comment]
The first issue you describe is expected, since any model that was previously edited by external tools through the XMLA endpoint, can no longer be downloaded or edited in the service (see the [caution message here](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools#enhanced-metadata)). A workaround for that is to deploy the model through the [git integration of Fabric workspaces](https://learn.microsoft.com/en-us/fabric/cicd/git-integration/git-get-started?tabs=azure-devops%2CAzure%2Ccommit-to-git).

The second issue regarding refresh: Did you update the credentials for the new model, after you deployed it, as described in the blog post?

**Comment by patrickbcox** [comment]
Hi @otykier , thanks for your reply.  I decided to just recreate the model manually.  I was able to use TE3 to script my calculation groups and measures so that eased the pain.  I'll try this again in the future.  Thanks for your help.  :)
