### ISSUE TITLE
How to save as a Folder using Tabular Editor Command Line

### ISSUE THREAD

**Issue by tiagotfsilva** [TabularEditor/TabularEditor#1234]
When running the following shell command only one file is generated (database.json) which looks like the .bim file. It doesn't create the whole folder structure. Any advice? 

`& "$tabularEditorPath" "$bimFilePath" -F "$folderPath"`

**Comment by tiagotfsilva** [comment]
I have Tabular Editor 2.25.0

**Comment by otykier** [comment]
Hi @tiagotfsilva 
The issue is that the bim file does not contain the specification on how the model should be serialized. This specification is stored as an annotation on the model. The easiest option is to load the model once in the TE UI, then go to **File > Preferences > Current Model** and set the checkmarks according to the depth of serialization you would like to have:

![image](https://github.com/user-attachments/assets/6c16bd9e-1ab4-4eec-97ca-abb6b01f614f)

After clicking "OK", you should see the following annotation on the model:

![image](https://github.com/user-attachments/assets/35c290e9-1ee1-4d38-92df-d793dabb1e06)

If you then save the .bim with this annotation, then subsequently running the CLI with the `-F` switch should give you the folder structure you want.

Alternatively, you can use a C# script as part of the CLI execution to specify the same annotation. This way, you don't have to open the model in the TE UI. [Here is an example](https://github.com/TabularEditor/TabularEditor/issues/652#issuecomment-713435122) on how to do this.
