### ISSUE TITLE
Question: Database.json show perspectives on more then 1 line. 

### ISSUE THREAD

**Issue by Daandamhuis** [TabularEditor/TabularEditor#516]
Hi, 

I was working with the Master Model Pattern and we are working on it with several people incl. Git in AzureDevops. But sometimes we have an issue that there are conflicts in the database.json, because perspectives where added in different branches. Is it possible to show the perspectives "list" in database.json more "structure" than only on one line? 

This would help us a lot, considering that we are currently moving lots of models to the master model pattern.

```json
{
        "name": "TabularEditor_Perspectives",
        "value": "................"
}
```

**Comment by otykier** [comment]
Thanks for reporting this. I'm working on a new "save-to-folder" serialization mode, that uses ExtendedProperties instead of Annotations. The advantage of ExtendedProperties, is that it can save raw JSON, so that the resulting file will not have nested JSON like the annotations have today. This, in turn, avoids putting arrays and complex objects on a single line.

However, it will take some more time to finalise this, as I want to make sure I cover all aspects of save-to-folder serialization, such that each file generated is ideal for versioning/merge operations, keeping conflicts to a minimum.

**Comment by Daandamhuis** [comment]
Thanks for the reply! If you need someone to test it, I’ll be happy to help!
