### ISSUE TITLE
Advanced Scripting:  Allow for runtime input based on another model object / measure

### ISSUE THREAD

**Issue by sgeier4** [TabularEditor/TabularEditor#899]
In advanced scripting, allow the script to bring up a window that lists available model objects.  This new method could allow input to filter objects to display.  But the goal would be to return a DaxObjectName to be used in a measure.  

An application of this would be to select a denominator of a divide statement .  I could have the selected measures "Total Revenue" and "Total Quantity" and this new window could return Total shipments which could give you a revenue / shipment or quantity per shipment.

**Comment by otykier** [comment]
Hi @sgeier4 
This is already possible today using the [`SelectMeasure()` helper method](https://github.com/TabularEditor/TabularEditor/blob/885ff9f84f6497b7958a402854d959d747e0e0a2/TabularEditor/Scripting/ScriptHelper.cs#L48-L68), which is unfortunately quite poorly documented.

```csharp
// Displays a list of all measures in the model, prompting the user to select one.
var denominator = SelectMeasure();
if(denominator == null) 
    return;    // User didn't select anything
Info("You selected: " + denominator.DaxObjectName);
```

You can also specify a list of specific measures to display to the user, instead of all model measures:

```csharp
var denominator = SelectMeasure(Model.Tables["Internet Sales"].Measures);
```

Or if you want to change the lable at the top of the prompt:

```csharp
var denominator = SelectMeasure(label: "Choose denominator:");
```

![image](https://user-images.githubusercontent.com/8976200/127821830-20698981-bebd-49ff-967a-ccd6e5146876.png)

**Comment by sgeier4** [comment]
Thanks @otykier as this helps a ton.  You could almost copy and past this example into the documentation and would be clear to anyone that's trying to do the same.  Thanks again.
