### ISSUE TITLE
Calculation group items translation

### ISSUE THREAD

**Issue by yh156** [TabularEditor/TabularEditor#944]
Hello ! 

I'm providing translated Power BI model to my users, but I can't find the option to translate calculation group items. Is there any way to do that ? 

Thanks

**Comment by otykier** [comment]
It's not possible to add metadata translations to calculation items, since the items are not metadata but actual data stored within the calculation group table, and Power BI / AS tabular does not support data translations. For one possible workaround (which is not specific to calculation items), see here: https://blog.crossjoin.co.uk/2021/02/21/implementing-data-as-well-as-metadata-translations-in-power-bi/
