### ISSUE TITLE
 Calculation Group,the sign`∑` disappeared

### ISSUE THREAD

**Issue by jiaopengzi** [TabularEditor/TabularEditor#970]
hi @otykier 
I came again.
This 
a new power bi pbix,In the number field, there is the corresponding identifier: `∑`;

As shown in figure:
![1](https://user-images.githubusercontent.com/52224629/155868904-d2cb33c5-7b40-4c39-9a6a-bcb95f03f713.png)

**But,add Calculation Group,the sign`∑` disappeared;and the corresponding field becomes a text type, and can not drag and drop in values,but `Sum` is available.**

As shown in figure:
![2](https://user-images.githubusercontent.com/52224629/155869052-43568e6d-e6d4-4fed-9076-4d7c8b9932c0.png)

I don't know if it's my problem or a bug. Please help me check it out. Thank you very much.

**Application specifics**
 - Tabular Editor 2.X version: [2.16.5] and [3.2.2] 
 - Semantic Engine used: [Power BI Desktop]

**Comment by otykier** [comment]
This is by design. [Calculation Groups require that the Model property **DiscourageImplicitMeasures** is set to true](https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions#:~:text=DiscourageImplicitMeasures).

This is also discussed [here](https://github.com/TabularEditor/TabularEditor/issues/544).
